[Params]

  ## CSES Standings config
  ### IMPORTANT: The external API uses this file, and the `csesIds` config to fetch the user ids

  csesIds   = [ 69586,   74066,         74546,    72385,   83700,     74173,     58188,      107392, 49524,  109224, 87807,     114566, 114575,  114576]
  csesNames = ["Blaz", "wawer",  "Marinkovic", "Dmitri", "Jayki", "Davicom", "dariasc", "AngrySeal",  "vi", "frann",   "J", "MichaelS", "m1tu", "Brito"]
  csesEndpoint = "https://uchile.davicom.cl/api/cses-tasks/"
  csesProblemUrl = "https://cses.fi/problemset/task/"
  csesCacheLife = 300 # in seconds
